In [2]:
import numpy as np
import pandas as pd

## __COMBINING Original A1 dataset and supplement A3 dataset into__

In [3]:
df = pd.read_csv('datasets\starting datasets\drug_deaths.csv')
sup_df = pd.read_csv('datasets\starting datasets\drug_deaths_supplement(A3).csv')

In [5]:
sup_df

,Date,Sex,Race,Age,ResidenceCity,ResidenceCounty,DeathCity,DeathCounty,Location,InjuryPlace,...,Ethanol,Hydrocodone,Benzodiazepine,Methadone,Amphet,Tramad,Hydromorphone,Morphine,OpiateNOS,AnyOpioid
0,1/1/2019,Male,White,58,Bridgeport,Fairfield,Bridgeport,Fairfield,Hospital,Residence,...,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y
1,1/1/2019,Male,Black,22,Norwalk,Fairfield,Norwalk,Fairfield,Other,"Other, Residential Institution",...,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,Y
2,1/1/2019,Male,"Hispanic, White",60,Waterbury,New Haven,Waterbury,New Haven,Residence,Residence,...,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,Y
3,1/1/2019,Male,"Hispanic, White",33,Meriden,New Haven,Meriden,New Haven,Residence,Residence,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y
4,1/2/2019,Male,White,24,Glastonbury,Hartford,Glastonbury,Hartford,Residence,Residence,...,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,12/30/2019,Female,White,52,West Haven,New Haven,West Haven,New Haven,Residence,Residence,...,Y,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,Y
1196,12/31/2019,Female,White,58,Windsor,Hartford,Hartford,Hartford,Hospital,"Other, Residential Institution",...,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,Y
1197,12/31/2019,Male,"Hispanic, White",28,Bridgeport,Fairfield,Bridgeport,Fairfield,Residence,Residence,...,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y
1198,12/31/2019,Male,Black,58,Hartford,Hartford,Hartford,Hartford,Other,"Other, Residential Institution",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y
1199,12/31/2019,Female,White,32,Norwalk,Fairfield,Norwalk,Fairfield,Residence,Residence,...,NaN,NaN,Y,NaN,Y,NaN,NaN,NaN,NaN,Y

In [6]:
# List of columns to process
columns_to_process = [
    'Heroin', 'Cocaine', 'Fentanyl', 'Fentanyl_Analogue', 'Oxycodone',
    'Oxymorphone', 'Ethanol', 'Hydrocodone', 'Benzodiazepine', 'Methadone',
    'Amphet', 'Tramad', 'Hydromorphone', 
    'OpiateNOS', 'AnyOpioid'
]

# Convert 'Y' to 1 and other values to 0
sup_df[columns_to_process] = sup_df[columns_to_process].applymap(lambda x: 1 if x == 'Y' else 0)

In [7]:

sup_df['no_of_drugs'] = sup_df[columns_to_process].sum(axis=1)
############################################################################################################
sup_df['InjuriesPerRace'] = sup_df.groupby('Race')['Race'].transform('count')
############################################################################################################
# Group by 'death county' and count the number of deaths in each county
sup_df['DeathsPercounty'] = sup_df.groupby('DeathCounty')['DeathCounty'].transform('count')
############################################################################################################
sup_df['ResidentsPerCounty'] = sup_df.groupby('ResidenceCity')['ResidenceCity'].transform('count')
############################################################################################################
# Group by 'DeathCity' and count the number of deaths per city
sup_df['InjuriesPerCounty'] = sup_df.groupby('InjuryCounty')['InjuryCounty'].transform('count')
############################################################################################################
# Add a new column with the count of residents per city
sup_df['ResidentsPerCity'] = sup_df.groupby('ResidenceCity')['ResidenceCity'].transform('count')
############################################################################################################
sup_df['InjuriesPerCity'] = sup_df.groupby('InjuryCity')['InjuryCity'].transform('count')
############################################################################################################
sup_df['DeathsPerCity'] = sup_df.groupby('DeathCity')['DeathCity'].transform('count')

sup_df

,Date,Sex,Race,Age,ResidenceCity,ResidenceCounty,DeathCity,DeathCounty,Location,InjuryPlace,...,OpiateNOS,AnyOpioid,no_of_drugs,InjuriesPerRace,DeathsPercounty,ResidentsPerCounty,InjuriesPerCounty,ResidentsPerCity,InjuriesPerCity,DeathsPerCity
0,1/1/2019,Male,White,58,Bridgeport,Fairfield,Bridgeport,Fairfield,Hospital,Residence,...,0,1,4,865.0,179.0,60.0,170.0,60.0,67.0,80
1,1/1/2019,Male,Black,22,Norwalk,Fairfield,Norwalk,Fairfield,Other,"Other, Residential Institution",...,0,1,5,133.0,179.0,19.0,170.0,19.0,17.0,18
2,1/1/2019,Male,"Hispanic, White",60,Waterbury,New Haven,Waterbury,New Haven,Residence,Residence,...,0,1,4,172.0,364.0,89.0,355.0,89.0,109.0,125
3,1/1/2019,Male,"Hispanic, White",33,Meriden,New Haven,Meriden,New Haven,Residence,Residence,...,0,1,2,172.0,364.0,18.0,355.0,18.0,23.0,25
4,1/2/2019,Male,White,24,Glastonbury,Hartford,Glastonbury,Hartford,Residence,Residence,...,0,1,4,865.0,375.0,1.0,350.0,1.0,2.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,12/30/2019,Female,White,52,West Haven,New Haven,West Haven,New Haven,Residence,Residence,...,0,1,5,865.0,364.0,20.0,355.0,20.0,25.0,19
1196,12/31/2019,Female,White,58,Windsor,Hartford,Hartford,Hartford,Hospital,"Other, Residential Institution",...,0,1,4,865.0,375.0,10.0,350.0,10.0,8.0,169
1197,12/31/2019,Male,"Hispanic, White",28,Bridgeport,Fairfield,Bridgeport,Fairfield,Residence,Residence,...,0,1,4,172.0,179.0,60.0,170.0,60.0,67.0,80
1198,12/31/2019,Male,Black,58,Hartford,Hartford,Hartford,Hartford,Other,"Other, Residential Institution",...,0,1,4,133.0,375.0,96.0,350.0,96.0,133.0,169
1199,12/31/2019,Female,White,32,Norwalk,Fairfield,Norwalk,Fairfield,Residence,Residence,...,0,1,5,865.0,179.0,19.0,170.0,19.0,17.0,18

In [9]:
df['Fentanyl'] = pd.to_numeric(df['Fentanyl'], errors='coerce').astype('Int64')
df['AnyOpioid'] = pd.to_numeric(df['AnyOpioid'], errors='coerce').astype('Int64')

In [10]:
df['no_of_drugs'] = df[columns_to_process].sum(axis=1)
############################################################################################################
df['InjuriesPerRace'] = df.groupby('Race')['Race'].transform('count')
############################################################################################################
# Group by 'death county' and count the number of deaths in each county
df['DeathsPercounty'] = df.groupby('DeathCounty')['DeathCounty'].transform('count')
############################################################################################################
df['ResidentsPerCounty'] = df.groupby('ResidenceCity')['ResidenceCity'].transform('count')
############################################################################################################
# Group by 'DeathCity' and count the number of deaths per city
df['InjuriesPerCounty'] = df.groupby('InjuryCounty')['InjuryCounty'].transform('count')
############################################################################################################
# Add a new column with the count of residents per city
df['ResidentsPerCity'] = df.groupby('ResidenceCity')['ResidenceCity'].transform('count')
############################################################################################################
df['InjuriesPerCity'] = df.groupby('InjuryCity')['InjuryCity'].transform('count')
############################################################################################################
df['DeathsPerCity'] = df.groupby('DeathCity')['DeathCity'].transform('count')

df

,Date,Age,Sex,Race,ResidenceCity,ResidenceCounty,DeathCity,DeathCounty,Location,InjuryPlace,...,ResidenceCityGeo,InjuryCityGeo,no_of_drugs,InjuriesPerRace,DeathsPercounty,ResidentsPerCounty,InjuriesPerCounty,ResidentsPerCity,InjuriesPerCity,DeathsPerCity
0,6/28/2014 0:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"CT\n(41.575155, -72.738288)","CT\n(41.575155, -72.738288)",3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3/21/2013 0:00,48.0,Male,Black,NORWALK,NaN,NORWALK,FAIRFIELD,Hospital,NaN,...,"NORWALK, CT\n(41.11805, -73.412906)","CT\n(41.575155, -72.738288)",1,433.0,623.0,57.0,NaN,57.0,NaN,69.0
2,3/13/2016 0:00,30.0,Female,White,SANDY HOOK,FAIRFIELD,DANBURY,NaN,Hospital,Unknown,...,"SANDY HOOK, CT\n(41.419998, -73.282501)",NaN,3,4004.0,NaN,5.0,NaN,5.0,70.0,131.0
3,3/31/2016 0:00,23.0,Male,White,RYE,WESTCHESTER,GREENWICH,NaN,Hospital,Residence,...,NaN,NaN,3,4004.0,NaN,3.0,NaN,3.0,1.0,22.0
4,2/13/2013 0:00,22.0,Male,"Asian, Other",FLUSHING,QUEENS,GREENWICH,FAIRFIELD,Hospital,Other,...,NaN,"CT\n(41.575155, -72.738288)",1,18.0,623.0,1.0,NaN,1.0,NaN,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5100,9/8/2015 0:00,43.0,Male,White,CHESHIRE,NEW HAVEN,CHESHIRE,NEW HAVEN,Residence,Residence,...,"CHESHIRE, CT\n(41.498834, -72.901448)","CT\n(41.575155, -72.738288)",2,4004.0,1107.0,22.0,NaN,22.0,NaN,8.0
5101,7/22/2017 0:00,21.0,Male,White,MADISON,NEW HAVEN,NEW HAVEN,NEW HAVEN,Hospital,In Vehicle,...,"MADISON, CT\n(41.271447, -72.60086)","CT\n(41.575155, -72.738288)",2,4004.0,1107.0,17.0,NaN,17.0,NaN,374.0
5102,8/14/2018 0:00,30.0,Male,White,LAWRENCEVILLE,TIOGA,DANBURY,FAIRFIELD,Other,Hotel or Motel,...,NaN,"DANBURY, CT\n(41.393666, -73.451539)",5,4004.0,623.0,1.0,371.0,1.0,61.0,131.0
5103,3/16/2014 0:00,33.0,Male,White,HARTFORD,NaN,WINDSOR,NaN,Other,Hotel or Motel,...,"HARTFORD, CT\n(41.765775, -72.673356)","CT\n(41.575155, -72.738288)",1,4004.0,NaN,296.0,NaN,296.0,NaN,24.0
5104,9/15/2016 0:00,33.0,Male,White,THOMASTON,LITCHFIELD,WATERBURY,NaN,Other,Railroad Track,...,"THOMASTON, CT\n(41.674124, -73.073189)","WATERBURY, CT, CT\n(41.554261, -73.043069)",2,4004.0,NaN,11.0,NaN,11.0,2.0,368.0

In [11]:
# Concatenate the DataFrames while preserving all columns
combined_df = pd.concat([df,sup_df], ignore_index=True)


# Save the combined DataFrame to a new CSV
combined_df.to_csv('combined2.csv', index=False)
combined_df

,Date,Age,Sex,Race,ResidenceCity,ResidenceCounty,DeathCity,DeathCounty,Location,InjuryPlace,...,no_of_drugs,InjuriesPerRace,DeathsPercounty,ResidentsPerCounty,InjuriesPerCounty,ResidentsPerCity,InjuriesPerCity,DeathsPerCity,Cause of Death,Morphine
0,6/28/2014 0:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3/21/2013 0:00,48.0,Male,Black,NORWALK,NaN,NORWALK,FAIRFIELD,Hospital,NaN,...,1,433.0,623.0,57.0,NaN,57.0,NaN,69.0,NaN,NaN
2,3/13/2016 0:00,30.0,Female,White,SANDY HOOK,FAIRFIELD,DANBURY,NaN,Hospital,Unknown,...,3,4004.0,NaN,5.0,NaN,5.0,70.0,131.0,NaN,NaN
3,3/31/2016 0:00,23.0,Male,White,RYE,WESTCHESTER,GREENWICH,NaN,Hospital,Residence,...,3,4004.0,NaN,3.0,NaN,3.0,1.0,22.0,NaN,NaN
4,2/13/2013 0:00,22.0,Male,"Asian, Other",FLUSHING,QUEENS,GREENWICH,FAIRFIELD,Hospital,Other,...,1,18.0,623.0,1.0,NaN,1.0,NaN,22.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6300,12/30/2019,52.0,Female,White,West Haven,New Haven,West Haven,New Haven,Residence,Residence,...,5,865.0,364.0,20.0,355.0,20.0,25.0,19.0,Acute intoxication due to the combined effects...,NaN
6301,12/31/2019,58.0,Female,White,Windsor,Hartford,Hartford,Hartford,Hospital,"Other, Residential Institution",...,4,865.0,375.0,10.0,350.0,10.0,8.0,169.0,Complications of Acute and Chronic Substance A...,NaN
6302,12/31/2019,28.0,Male,"Hispanic, White",Bridgeport,Fairfield,Bridgeport,Fairfield,Residence,Residence,...,4,172.0,179.0,60.0,170.0,60.0,67.0,80.0,"Multidrug Toxicity Including Ethanol, Cocaine,...",NaN
6303,12/31/2019,58.0,Male,Black,Hartford,Hartford,Hartford,Hartford,Other,"Other, Residential Institution",...,4,133.0,375.0,96.0,350.0,96.0,133.0,169.0,Acute Intoxication by the Combined Effects of ...,NaN
6304,12/31/2019,32.0,Female,White,Norwalk,Fairfield,Norwalk,Fairfield,Residence,Residence,...,5,865.0,179.0,19.0,170.0,19.0,17.0,18.0,"Acute intoxication fentanyl, heroin, alprazola...",NaN

In [ ]:
combined_df = pd.read_csv('datasets/final datasets/combined2.csv')
columns_to_sum = ['Heroin', 'Cocaine', 'Fentanyl', 'Fentanyl_Analogue', 'Oxycodone',
    'Oxymorphone', 'Ethanol', 'Hydrocodone', 'Benzodiazepine', 'Methadone',
    'Amphet', 'Tramad', 'Hydromorphone', 'Morphine',
    'OpiateNOS', 'AnyOpioid']

# Calculate the sum of the specified columns
selected_sums = combined_df[columns_to_sum].sum()

# Sort the sums in descending order
sorted_sums = selected_sums.sort_values(ascending=False)
sorted_sums

FileNotFoundError: [Errno 2] No such file or directory: 'datasets/final datasets/combined2.csv'